version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-133-42.compute-1.amazonaws.com
            port: '5432'
            database: dfv9hpbu6h1j7l
            ssl: true
            user: rbhsrtwlzcevrz
            password: dbf02d3bce0f63141a2d7e0468235dbcb2a9f2d8050c5e7a9706e2cd392a3136
            migrations: true